### PR TITLE
#900 - Fix FirstOrder and FirstOrderZonotope with zero matrix

### LINKED ISSUE #900: First-order discretization for affine dynamics with zero matrix crashes
```julia
A = zeros(2, 2)
c = zeros(2)
X0 = BallInf(c, 1.0);
prob = @ivp(x' = A * x + c, x(0) ∈ X0)
alg = GLGM06(δ=0.1)
tspan = (0.0, 1.0)
sol = solve(prob; tspan, alg)
```

The problem is that $‖A‖ = 0$ and the discretization algorithms `FirstOrder` and `FirstOrderZonotope` divide by this quantity, creating a `NaN` result.

### PR DESCRIPTION
**Pull request by alecarraro**
Closes #900.

### CODE REVIEW

File: src/Discretization/FirstOrderZonotopeModule.jl [hunk 1]
```diff
@@ -103,7 +104,9 @@ function discretize(ivp::IVP{<:CLCCS,<:AbstractZonotope}, δ, alg::FirstOrderZon
     # compute bloating factor β
     U = next_set(inputset(ivp), 1)
     μ = norm(U, Inf)
-    β = ((exp(norm_A * δ) - 1) * μ) / norm_A
```
Comment (schillic) [inline src/Discretization/FirstOrderZonotopeModule.jl:106]: Please do not add two empty lines (at most one).

I think the `norm_A ==` part should be removed.

Any reason to rewrite the "else" case? I suggest to keep the old expression.

**Review by schillic — APPROVED** [review]
Thanks!
